"""
Django settings for baize_backend project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import dotenv
from pathlib import Path
import os
from datetime import timedelta

dotenv.load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'baize_backend.urls'

AUTH_USER_MODEL = 'user.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'baize_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PRIVATE_KEY_PATH = os.path.join(BASE_DIR, 'certs', 'private.pem')
PUBLIC_KEY_PATH = os.path.join(BASE_DIR, 'certs', 'public.pem')

SIMPLE_JWT = {
    # === 有效期配置 ===
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),   # Access Token 有效期 (默认5分钟)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # Refresh Token 有效期 (默认1天)

    # === 刷新策略 (可选) ===
    'ROTATE_REFRESH_TOKENS': False, # 刷新Token时是否同时换发新的Refresh Token
    'BLACKLIST_AFTER_ROTATION': False, # 换发新Refresh后，旧的立即加入黑名单(需启用黑名单应用)

    # === 请求头与格式 ===
    'AUTH_HEADER_TYPES': ('Bearer',),   # 请求头前缀，支持多个如 ('Bearer', 'JWT')
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION', # 对应的Meta名称

    # === Token 中的数据 ===
    'USER_ID_FIELD': 'id',           # 用户模型中的主键字段
    'USER_ID_CLAIM': 'user_id',      # Payload 中存储用户ID的键名

    'ALGORITHM': 'RS256', 

    'SIGNING_KEY': open(PRIVATE_KEY_PATH, 'r').read(), 
    'VERIFYING_KEY': open(PUBLIC_KEY_PATH, 'r').read(),
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTStatelessUserAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
